### ISSUE TITLE
Re-registration doesn't work, it registers only once.

### ISSUE THREAD

**Issue by prathibhacdac** [onsip/SIP.js#1071]
First time the registration occurs and it is successful. After 5 mins, it re-registers and goes to "Unregistered, Bye" state. After that nothing happens.

browser console log:

sip-0.20.0.min.js:2 Tue Mar 05 2024 17:44:07 GMT+0530 (India Standard Time) | sip.Registerer | An attempt was made to send a REGISTER request while a prior one was still in progress. RFC 3261 requires UAs MUST NOT send a new registration until they have received a final response from the registrar for the previous one or the previous REGISTER request has timed out. Note that if the transport disconnects, you still must wait for the prior request to time out before sending a new REGISTER request or alternatively dispose of the current Registerer and create a new Registerer.
sip-0.20.0.min.js:2 Uncaught (in promise) Error: REGISTER request already in progress, waiting for final response
    at he.register (sip-0.20.0.min.js:2:110877)
    at sip-0.20.0.min.js:2:116504
sip-0.20.0.min.js:2 Tue Mar 05 2024 17:44:09 GMT+0530 (India Standard Time) | sip.Registerer | Registration expired

**Comment by unadlib** [comment]
Any updates?

**Comment by unadlib** [comment]
The same issue exists in SIP.js v0.13.5, and it is currently suspected that this may be due to unexpected behavior of timers (registrationTimer and registrationExpiredTimer).

Relevant code: https://github.com/onsip/SIP.js/blob/0.13.5/src/RegisterContext.ts#L296

Is it possible for you to provide an API for custom timer functions?

For example, APIs like `externalSetTimeout` and `externalClearTimeout`.

Related links:

- [Background timer alignment](https://developer.chrome.com/blog/background_tabs#background_timer_alignment)
- [Timer throttling in Chrome 88](https://developer.chrome.com/blog/timer-throttling-in-chrome-88)
