### ISSUE TITLE
Media not supported

### ISSUE THREAD

**Issue by excendia** [onsip/SIP.js#194]
I have the error message "Media not supported" when trying to make an outbound calls. 

Here the function called from my cordova android application:

``` javascript
function CallSIP(phone, selfView, remoteView)
{
    var session;          
    if(userAgent.isConnected())
    {
        var options = {
            media: {
                constraints: {
                    audio: true,
                    video: false
                },
                render: {
                    remote: remoteView,
                    local: selfView
                }
            }
        }

        //makes the call 
        var domain = 'ets1.excenida.com';
        var target = phone + '@' + domain;

        session = userAgent.invite(target, options);
    }
}
```

and the html is:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'" />
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
    <title>Hello World</title>	
    
    <link rel="stylesheet" type="text/css" href="css/index.css">
    <link rel="stylesheet" type="text/css" href="css/styles.css">
    <link href="css/font-awesome.css" rel="stylesheet">
    
<script language="javascript" type="text/javascript" src="js/jquery.js"></script>
    <script language="javascript" type="text/javascript" src="js/sip.js"></script>
<script>
        $(document).ready(function(e){
            
            $(".phone").on("touchstart",function(){                  
                
                var selfView =   document.getElementById('localVideo');
                var remoteView =  document.getElementById('remoteVideo');
                var audioView =  document.getElementById('audio_remote');
                
                CallSIPml1($("#textNumber").html(), selfView, remoteView, audioView);

            });       
            
            $(".key").on("touchstart",function(){
                var $digit = $(this).attr("rel");
                if($digit !== 'Make Call')
                {
                    $("#textNumber").html($("#textNumber").html() + $digit);
                }
            });
        });
    </script>

</head>
<body>
    
    <div style="display: none">
        <audio id="audio_remote" autoplay="autoplay" />
        <video id="remoteVideo" autoplay="autoplay"></video>
        <video id="localVideo" autoplay="autoplay" muted="true"></video>
    </div>
        
    <h1 id="textNumber">1000</h1>
    <div id="phone"> 
        <div id="wrapper">    
            <div class="key" rel="1">1</div>
            <div class="key" rel="2">2<span>abc</span></div>
            <div class="key" rel="3">3<span>def</span></div>
            <div class="clear"></div>
            <div class="key" rel="4">4<span>ghi</span></div>
            <div class="key" rel="5">5<span>jkl</span></div>
            <div class="key" rel="6">6<span>mno</span></div>
            <div class="clear"></div>
            <div class="key" rel="7">7<span>pqrs</span></div>
            <div class="key" rel="8">8<span>tuv</span></div>
            <div class="key" rel="9">9<span>wxyz</span></div>
            <div class="clear"></div>
            <div class="key special" rel="*">*</div>
            <div class="key" rel="0">0<span>oper</span></div>
            <div class="key special" rel="#">#</div>
            <div class="clear"></div>
            <div class="key nb"></div>
            <div class="key phone" rel="Make Call"><i class="fa fa-phone"></i></div>
            <div class="key nb"></div>
            <div class="clear"></div>
        </div>
    </div>
    
</body>
</html>
```

**Comment by dbmikus** [comment]
If there's a stack trace for the "Media not supported" error, could you post that?

It seems like your Android Cordova application does not have access to WebRTC. If that's the case, the [SIP.js mailing list](https://groups.google.com/forum/#!forum/sip_js) is a better place for troubleshooting.

**Comment by excendia** [comment]
Here is the stack trace:

Tue Jun 30 2015 09:42:55 GMT-0400 (EDT) | sip.invitecontext.mediahandler | acquiring local media (09:42:57:882)
  at www/js/sip.js:36
Tue Jun 30 2015 09:42:55 GMT-0400 (EDT) | sip.invitecontext.mediahandler | unable to acquire streams (09:42:57:929 | error)
    at c.print (www/js/sip.js:36:27912)
    at c.(anonymous function) (www/js/sip.js:36:28105)
    at b.(anonymous function) (www/js/sip.js:36:27999)
    at (anonymous function) (www/js/sip.js:40:13333)
[object NavigatorUserMediaError] (09:42:57:944 | error)
    at c.print (www/js/sip.js:36:27912)
    at c.(anonymous function) (www/js/sip.js:36:28105)
    at b.(anonymous function) (www/js/sip.js:36:27999)
    at (anonymous function) (www/js/sip.js:40:13377)

Furthermore, I attempted to use 
var audioContext = new (window.AudioContext || window.webkitAudioContext)();
    var options = {
        media: {
      stream: audioContext.createMediaStreamDestination().stream
    }
Which calls the number, but there is no sound. Therefore, there has to be a way to enable the microphone for getUserMedia?

**Comment by wakamoleguy** [comment]
Cordova isn't officially supported at this time.  Based on the error, it does look like your application is/was lacking microphone access.  In terms of how to enable it, though, we unfortunately cannot help.
