### ISSUE TITLE
 pc.getSenders error in phone 

### ISSUE THREAD

**Issue by yuexiajiayan** [onsip/SIP.js#656]
Error {message: "pc.getSenders is not a fu...

message: "pc.getSenders is not a function"

stack: "TypeError: pc.getSenders is not a function at InviteClientContext.<anonymous> (https://ip/HBBKTEST/sip/a.html:129:9) at InviteClientContext.emit (https://ip/HBBKTEST/sip/sip-0.13.5.js:479:5) at SessionDescriptionHandlerObserver.trackAdded (https://ip/HBBKTEST/sip/sip-0.13.5.js:24891:22) at https://ip/HBBKTEST/sip/sip-0.13.5.js:24594:36 at <anonymous>"

in chrome is ok in phone other intenet like this

**Comment by yuexiajiayan** [comment]
> Error {message: "pc.getSenders is not a fu...
> 
> message: "pc.getSenders is not a function"
> 
> stack: "TypeError: pc.getSenders is not a function at InviteClientContext. (https://ip/HBBKTEST/sip/a.html:129:9) at InviteClientContext.emit (https://ip/HBBKTEST/sip/sip-0.13.5.js:479:5) at SessionDescriptionHandlerObserver.trackAdded (https://ip/HBBKTEST/sip/sip-0.13.5.js:24891:22) at https://ip/HBBKTEST/sip/sip-0.13.5.js:24594:36 at "
> 
> in chrome is ok in phone other intenet like this
