### ISSUE TITLE
Must use import to load ES Module: \sip.js\lib\index.js I face this issue in 0.17.1 version 

### ISSUE THREAD

**Issue by MHamzaRajput** [onsip/SIP.js#854]
In my nodejs 
const SipJs = require('sip.js');
console.log(SipJs);

//=====================================//

internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: d:\webrtcdemo\WebrtcScratchSocketIo\node_modules\sip.js\lib\index.js
require() of ES modules is not supported.
require() of d:\webrtcdemo\WebrtcScratchSocketIo\node_modules\sip.js\lib\index.js from d:\webrtcdemo\WebrtcScratchSocketIo\backend\sipOverWeb.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from d:\webrtcdemo\WebrtcScratchSocketIo\node_modules\sip.js\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (d:\webrtcdemo\WebrtcScratchSocketIo\backend\sipOverWeb.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'ERR_REQUIRE_ESM'
}

Kindly tell me what is the issue

**Comment by james-criscuolo** [comment]
Use `import` instead of `require`, or use the `esm` package to wrap `require`

**Comment by alisherafat01** [comment]
same problem in `0.21.2` version and I'm not using `require` in codebase. 
Any idea?
